# Generated by Django 2.1.3 on 2018-12-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('idChat', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('photoPath', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('idRoom', models.AutoField(primary_key=True, serialize=False)),
                ('nameRoom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.Rooms'),
        ),
        migrations.AddField(
            model_name='chats',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Profile.UserProfil'),
        ),
    ]
