# Generated by Django 2.1.3 on 2018-12-09 20:01

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chats_photopath'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='photo',
            field=models.ImageField(blank=True, upload_to=chat.models.UploadTo),
        ),
    ]
