# Generated by Django 2.1.3 on 2018-12-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='DateBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
