# Generated by Django 2.1.3 on 2018-12-02 21:24

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20181202_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='photo',
            field=models.ImageField(upload_to=Profile.models.UploadTo),
        ),
    ]
